<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - Flight Search Test</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>Flight Search Test</h1>
<p>
  Test duration: 43.628s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.pf.TestCases.FlightSearchTest</td>
      </tr>
            
<tr>
  <td class="method">
                  flightSearchTest
      </td>
  <td class="duration">
    43.628s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (2):<br/>
<br/>
Failure 1 of 2:<br/>
java.lang.AssertionError: expected [6] but found [5]<br/>
	at org.testng.Assert.fail(Assert.java:97)<br/>
	at org.testng.Assert.assertEqualsImpl(Assert.java:136)<br/>
	at org.testng.Assert.assertEquals(Assert.java:118)<br/>
	at org.testng.Assert.assertEquals(Assert.java:563)<br/>
	at com.pf.ErrorCollectors.ErrorCollector.assertEquals(ErrorCollector.java:37)<br/>
	at com.pf.ErrorCollectors.ErrorCollector.verifyEquals(ErrorCollector.java:101)<br/>
	at com.pf.TestCases.FlightSearchTest.flightSearchTest(FlightSearchTest.java:24)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:498)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br/>
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br/>
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br/>
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br/>
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br/>
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br/>
	at java.util.ArrayList.forEach(ArrayList.java:1257)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:766)<br/>
	at org.testng.TestRunner.run(TestRunner.java:587)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1039)<br/>
	at org.testng.TestNG.run(TestNG.java:1007)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
<br/>
Failure 2 of 2:<br/>
java.lang.AssertionError: expected [7] but found [5]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:97)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:136)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:563)<br />
              com.pf.ErrorCollectors.ErrorCollector.assertEquals(ErrorCollector.java:37)<br />
              com.pf.ErrorCollectors.ErrorCollector.verifyEquals(ErrorCollector.java:101)<br />
              com.pf.TestCases.FlightSearchTest.flightSearchTest(FlightSearchTest.java:25)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:498)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br />
              org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br />
              org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br />
              org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br />
              org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br />
              org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.util.ArrayList.forEach(ArrayList.java:1257)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:766)<br />
              org.testng.TestRunner.run(TestRunner.java:587)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:286)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br />
              org.testng.TestNG.runSuites(TestNG.java:1039)<br />
              org.testng.TestNG.run(TestNG.java:1007)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
